homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),

    
]

story/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth.views import auth_logout
from homepage.views import loginUser, logoutUser, register


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('login', loginUser, name="login"),
    path('register', register, name='register'),
    path('logout', logoutUser, name='logout')
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/forms.py
from django import forms

class UserForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control width-50vw',
        'id':'user',
        'placeholder': 'Example: danadani',
        'name':'user'
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class':'form-control width-50vw',
        'id':'pswd',
        'placeholder': '********',
        'name':'pswd'
    }))

homepage/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from .forms import UserForm


def index(request):
    return render(request, 'index.html')

def register(request):
    if(request.method == 'POST'):
        form = UserCreationForm(request.POST);
        username = request.POST['username'];
        password = request.POST['password1'];

        if(form.is_valid()):
            User.objects.create_user(username=username, password=password);
            return redirect('/')

    else:
        form = UserCreationForm()

    return render(request, 'register.html',{'form':form})

def loginUser(request):
    if(request.method == 'POST'):
        form = UserForm(request.POST)
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if(user is not None ):
            login(request, user);   
            request.session.set_expiry(300)
            return redirect('/')
        else:
            return redirect('/login')

    else:
        form = UserForm()

    return render(request, 'login.html', {'form':form})

def logoutUser(request):
    logout(request)
    return redirect(reverse(loginUser))

homepage/templates/index.html
{% load static%}
{% block content %}

<!DOCTYPE html>

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}Home{% endblock %}</title>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">


  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

  <link href="https://fonts.googleapis.com/css?family=Yeon+Sung&display=swap" rel="stylesheet">

  <script src="{% static 'js/main.js' %}"></script>
</head>

<nav class="navbar"">
			<a href="{% url 'homepage:index' %}" style ="font-family : Yeon Sung; font-size : 40px; font-weight : Bold; color : #000">FPRADANA3</a>
			<div class="flex-left py-2 ml-auto">
					{% if user.is_authenticated %}
          <a href="/logout" class="btn btn-primary py-2 px-4">Sign out</a>
          {% else %}
          <a href="/login" class="btn btn-primary py-2 px-4">Sign in</a>
          {% endif %}
			</div>
	</nav>

<body style = "background-color : #fcf5b0">
	<div class="d-flex justify-content-center">
    <h1 class="text-big mb-4" style ="font-family : Yeon Sung; font-weight : Bold">Halo{% if user.is_authenticated %} {{user.get_username}}{% endif %}, Selamat Datang!</h1>
	</div>


	</body>
</html>
{% endblock %}

homepage/templates/login.html
{% load static%}
{% block content %}

<!DOCTYPE html>

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}Login{% endblock %}</title>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">


  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

  <link href="https://fonts.googleapis.com/css?family=Yeon+Sung&display=swap" rel="stylesheet">

  <script src="{% static 'js/main.js' %}"></script>
</head>

<nav class="navbar"">
			<a href="{% url 'homepage:index' %}" style ="font-family : Yeon Sung; font-size : 40px; font-weight : Bold; color : #000">FPRADANA3</a>
			<div class="flex-left py-2 ml-auto">
					{% if user.is_authenticated %}
          <a href="/logout" class="btn btn-primary py-2 px-4">Sign out</a>
          {% else %}
          <a href="/login" class="btn btn-primary py-2 px-4">Sign in</a>
          {% endif %}
			</div>
	</nav>

<body style = "background-color : #fcf5b0">
	<div class="container section-container flex-center-col p-5">
    <h1 class="text-24 bold ">Log in</h1>
    <form method="post" class="flex-center-col" action="{% url 'login' %}">
        {% csrf_token %}
        <div class="form-container mt-2">
            <label for="user" class="text-12">Username:</label>
            {{form.username}}
        </div>
        <div class="form-container mt-2">
            <label for="pswd" class="text-12">Password:</label>
            {{form.password}}
        </div>
        <button class="btn btn-primary my-4 py-2 px-5" name="login" id="login">Login</button>
    </form>
    <div class="flex-center-col ">
        <p class="text-12 m-0">Belum terdaftar?</p>
        <a href="/register" class="text-12">Register</a>
    </div>
</div>



	</body>
</html>
{% endblock %}

homepage/templates/register.html
{% load static%}
{% block content %}

<!DOCTYPE html>

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}Register{% endblock %}</title>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">


  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

  <link href="https://fonts.googleapis.com/css?family=Yeon+Sung&display=swap" rel="stylesheet">

  <script src="{% static 'js/main.js' %}"></script>
</head>

<nav class="navbar"">
			<a href="{% url 'homepage:index' %}" style ="font-family : Yeon Sung; font-size : 40px; font-weight : Bold; color : #000">FPRADANA3</a>
			<div class="flex-left py-2 ml-auto">
					{% if user.is_authenticated %}
          <a href="/logout" class="btn btn-primary py-2 px-4">Sign out</a>
          {% else %}
          <a href="/login" class="btn btn-primary py-2 px-4">Sign in</a>
          {% endif %}
			</div>
	</nav>

<body style = "background-color : #fcf5b0">
	<div class="container section-container flex-center-col p-5">
    <h1 class="d-flex justify-content-center text-24" style="margin-bottom : 50px; font-weight: bold">Sign Up</h1>
    <form method="post" class="flex-center-col" action="{% url 'register' %}">
        {% csrf_token %}
        <div class="form-container mt-2">
            {{form}}
        </div>
        <button class="btn btn-primary my-4 py-2 px-5">Buat akun</button>
    </form>
    <div class="flex-center-col ">
        <p class="text-12 m-0">Punya akun?</p>
        <a href="/register" class="text-12">Sign in</a>
    </div>
</div>




	</body>
</html>
{% endblock %}